<a href="https://colab.research.google.com/github/abhishek-harihar/IIMI-ACPBDA/blob/main/Numpy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
my_list=[1,2,3,4,5]

In [4]:
type(my_list)

list

In [5]:
my_array=np.array(my_list)  #.array() function is used to convert list to array

In [6]:
type(my_array)

numpy.ndarray

In [7]:
#2 dimensional array
my_list_1=[1,2,3,4,5]
my_list_2=[11,12,13,14,15]
my_list_3=[21,22,23,24,25]

In [8]:
arr=np.array([my_list_1,my_list_2,my_list_3])

In [9]:
print(arr)

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]


In [10]:
type(arr)

numpy.ndarray

In [11]:
arr.shape #here 3 is number of rows and 5 is number of columns

(3, 5)

In [12]:
arr.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5, 11],
       [12, 13, 14],
       [15, 21, 22],
       [23, 24, 25]])

In [13]:
new_arr=np.array([[1,2,3,4],
 [5,6,7,8],
  [9,10,11,12]])

In [14]:
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
new_arr=new_arr.reshape(2,2,3)

In [16]:
print(new_arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [17]:
new_arr=new_arr.reshape(3,2,2)

In [18]:
print(new_arr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [19]:
# basic operations on single array

a=np.array([1,2,3,4,5])

print("add 1 to each element",a+1)

print("multiply 2 to each element",a*2)

print("square each element",a*a)  #a**2 for square

print("subtract 3 to each element",a-3)

add 1 to each element [2 3 4 5 6]
multiply 2 to each element [ 2  4  6  8 10]
square each element [ 1  4  9 16 25]
subtract 3 to each element [-2 -1  0  1  2]


In [ ]:
#unary operations
#binary operations